<wsdl:definitions targetNamespace="http://implementation.web.api.icc.services.osp.in.alcatel.com" xmlns:tns="http://implementation.web.api.icc.services.osp.in.alcatel.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns0="http://implementation.web.api.icc.services.osp.in.alcatel.com" xmlns:ns1="http://web.api.icc.services.osp.in.alcatel.com/xsd" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/">
 <wsdl:documentation>Suscriber All Information </wsdl:documentation>
 <wsdl:types>
  <xs:schema elementFormDefault="qualified">
   <xs:import namespace="http://implementation.web.api.icc.services.osp.in.alcatel.com" schemaLocation="subscriberLineManager.xsd"/>
   <xs:import namespace="http://web.api.icc.services.osp.in.alcatel.com/xsd" schemaLocation="wSHighLevelAPIException.xsd"/>
  </xs:schema>
 </wsdl:types>
 <wsdl:message name="getAllInformationRequest">
  <wsdl:part name="request" element="tns:getAllInformation"/>
 </wsdl:message>
 <wsdl:message name="getAllInformationResponse">
  <wsdl:part name="response" element="tns:getAllInformationResponse"/>
 </wsdl:message>
 <wsdl:message name="WSHighLevelAPIException">
  <wsdl:part name="fault" element="ns1:WSHighLevelAPIException"/>
 </wsdl:message>
 <wsdl:portType name="SubscriberLineManagerPortType">
  <wsdl:documentation>Consulta los datos Saldo</wsdl:documentation>
  <wsdl:operation name="getAllInformation">
   <wsdl:input name="request" message="tns:getAllInformationRequest"/>
   <wsdl:output name="response" message="tns:getAllInformationResponse"/>
   <wsdl:fault message="tns:WSHighLevelAPIException" name="WSHighLevelAPIException"/>
  </wsdl:operation>
 </wsdl:portType>
 <wsdl:binding name="SubscriberLineManagerPortTypeSOAP11Binding" type="tns:SubscriberLineManagerPortType">
  <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="getAllInformation">
   <soap:operation style="document" soapAction="http://implementation.web.api.icc.services.osp.in.alcatel.com/getAllInformation"/>
   <wsdl:input>
    <soap:body use="literal" parts="request"/>
   </wsdl:input>
   <wsdl:output>
    <soap:body use="literal" parts="response"/>
   </wsdl:output>
  </wsdl:operation>
 </wsdl:binding>
 <wsdl:service name="SubscriberLineManager">
  <wsdl:port name="SubscriberLineManagerSOAP11port_http" binding="tns:SubscriberLineManagerPortTypeSOAP11Binding">
   <soap:address location="http://10.96.74.15:8081/HighLevelApiWS-1.3/services/SubscriberLineManager"/>
  </wsdl:port>
 </wsdl:service>
</wsdl:definitions>