<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SearchBSCSBundleService/SearchBSCSBundleService/LocalWebPortalDba" name="LocalWebPortalDba-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SearchBSCSBundleService/SearchBSCSBundleService/LocalWebPortalDba" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SearchBSCSBundleService/SearchBSCSBundleService/LocalWebPortalDba" location="LocalWebPortalDba.wsdl"/>
  <binding name="LocalWebPortalDba_ptt-binding" type="tns:LocalWebPortalDba_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="LocalWebPortalDba">
      <soap:operation soapAction="LocalWebPortalDba"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="LocalWebPortalDba-service">
    <port name="LocalWebPortalDba-port" binding="tns:LocalWebPortalDba_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>