<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TrafficTypeApp/TrafficTypeProj/TrafficTypeSN" name="TrafficTypeSN-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TrafficTypeApp/TrafficTypeProj/TrafficTypeSN" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TrafficTypeApp/TrafficTypeProj/TrafficTypeSN" location="TrafficTypeSN.wsdl"/>
  <binding name="TrafficTypeSN_ptt-binding" type="tns:TrafficTypeSN_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="TrafficTypeSN">
      <soap:operation soapAction="TrafficTypeSN"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="TrafficTypeSN-service">
    <port name="TrafficTypeSN-port" binding="tns:TrafficTypeSN_ptt-binding">
      <soap:address location="jca://eis/DB/ConsultaTrafico"/>
    </port>
  </service>
</definitions>