<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ConsultaInfoLineaCliente/ValidaClienteGestorDB" name="ValidaClienteGestorDB-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ConsultaInfoLineaCliente/ValidaClienteGestorDB" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ConsultaInfoLineaCliente/ValidaClienteGestorDB" location="ValidaClienteGestorDB.wsdl"/>
  <binding name="ValidaClienteGestorDB_ptt-binding" type="tns:ValidaClienteGestorDB_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ValidaClienteGestorDB">
      <soap:operation soapAction="ValidaClienteGestorDB"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ValidaClienteGestorDB-service">
    <port name="ValidaClienteGestorDB-port" binding="tns:ValidaClienteGestorDB_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>