<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/CambioBolsaGestDBA" name="CambioBolsaGestDBA-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/CambioBolsaGestDBA" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/CambioBolsaGestDBA" location="CambioBolsaGestDBA.wsdl"/>
  <binding name="CambioBolsaGestDBA_ptt-binding" type="tns:CambioBolsaGestDBA_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="CambioBolsaGestDBA">
      <soap:operation soapAction="CambioBolsaGestDBA"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="CambioBolsaGestDBA-service">
    <port name="CambioBolsaGestDBA-port" binding="tns:CambioBolsaGestDBA_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>