<?binding.jca ConfigServiceCoreDBA_db.jca?><wsdl:definitions name="ConfigServiceCoreDBA" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/ConfigServiceCoreDBA" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConfigServiceCoreDBA" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/ConfigServiceCoreDBA" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ConfigServiceCoreDBA_plt">
        <plt:role name="ConfigServiceCoreDBA_role">
            <plt:portType name="tns:ConfigServiceCoreDBA_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConfigServiceCoreDBA" schemaLocation="ConfigServiceCoreDBA.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ConfigServiceCoreDBAInput_msg">
        <wsdl:part name="ConfigServiceCoreDBAInput_msg" element="db:ConfigServiceCoreDBAInput"/>
    </wsdl:message>
    <wsdl:message name="ConfigServiceCoreDBAOutputCollection_msg">
        <wsdl:part name="ConfigServiceCoreDBAOutputCollection" element="db:ConfigServiceCoreDBAOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConfigServiceCoreDBA_ptt">
        <wsdl:operation name="ConfigServiceCoreDBA">
            <wsdl:input message="tns:ConfigServiceCoreDBAInput_msg"/>
            <wsdl:output message="tns:ConfigServiceCoreDBAOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>