<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BSCSBundleService/GET_COFU_X_CODID/DBAGetCofuxCodId" name="DBAGetCofuxCodId-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BSCSBundleService/GET_COFU_X_CODID/DBAGetCofuxCodId" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BSCSBundleService/GET_COFU_X_CODID/DBAGetCofuxCodId" location="DBAGetCofuxCodId.wsdl"/>
  <binding name="DBAGetCofuxCodId_ptt-binding" type="tns:DBAGetCofuxCodId_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="DBAGetCofuxCodId">
      <soap:operation soapAction="DBAGetCofuxCodId"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="DBAGetCofuxCodId-service">
    <port name="DBAGetCofuxCodId-port" binding="tns:DBAGetCofuxCodId_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>