<WL5G3N0:definitions name="CONT.0010054.bundleProvisioning_1.0" targetNamespace="http://ws.wom.cl/WOM/NEG/ServiceOrderManagement/bundleProvisioning/v/1.0" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://ws.wom.cl/WOM/NEG/ServiceOrderManagement/bundleProvisioning/v/1.0" xmlns:WL5G3N2="http://schemas.xmlsoap.org/soap/envelope/" xmlns:WL5G3N3="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:flt="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inp1="http://ws.wom.cl/WOM/NEG/ServiceOrderManagement/bundleProvisioning/v/1.0" xmlns:inp2="http://ws.wom.cl/WOM/NEG/ServiceOrderManagement/bundleProvisioning/v/1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.wom.cl/WOM/NEG/ServiceOrderManagement/bundleProvisioning/v/1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://ws.wom.cl/WOM/NEG/ServiceOrderManagement/bundleProvisioning/v/1.0" schemaLocation="bundleProvisioningReq_1.0.xsd"/>
      <xsd:import namespace="http://ws.wom.cl/WOM/NEG/ServiceOrderManagement/bundleProvisioning/v/1.0" schemaLocation="bundleProvisioningResp_1.0.xsd"/>
      <xsd:import namespace="http://schemas.xmlsoap.org/soap/envelope/" schemaLocation="bundleProvisioningFault_1.0.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="bundleProvisioningMessageReq">
    <WL5G3N0:part element="WL5G3N1:bundleProvisioningReq" name="bundleProvisioningPart"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="bundleProvisioningMessageResp">
    <WL5G3N0:part element="WL5G3N1:bundleProvisioningResp" name="bundleProvisioningPart"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="bundleProvisioningMessageFault">
    <WL5G3N0:part element="WL5G3N2:Fault" name="bundleProvisioningPart"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="bundleProvisioning_ptt">
    <WL5G3N0:operation name="bundleProvisioning">
      <WL5G3N0:input message="WL5G3N1:bundleProvisioningMessageReq"/>
      <WL5G3N0:output message="WL5G3N1:bundleProvisioningMessageResp"/>
      <WL5G3N0:fault message="WL5G3N1:bundleProvisioningMessageFault" name="bundleProvisioningFault"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="bundleProvisioning_bind" type="WL5G3N1:bundleProvisioning_ptt">
    <WL5G3N3:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="bundleProvisioning">
      <WL5G3N3:operation soapAction="bundleProvisioning" style="document"/>
      <WL5G3N0:input>
        <WL5G3N3:body namespace="http://ws.wom.cl/WOM/NEG/ServiceOrderManagement/bundleProvisioning/v/1.0" use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N3:body namespace="http://ws.wom.cl/WOM/NEG/ServiceOrderManagement/bundleProvisioning/v/1.0" use="literal"/>
      </WL5G3N0:output>
      <WL5G3N0:fault name="bundleProvisioningFault">
        <WL5G3N3:fault name="bundleProvisioningFault" use="literal"/>
      </WL5G3N0:fault>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="bundleProvisioning_bindQSService">
    <WL5G3N0:documentation>OSB Service</WL5G3N0:documentation>
    <WL5G3N0:port binding="WL5G3N1:bundleProvisioning_bind" name="bundleProvisioning_bindQSPort">
      <WL5G3N3:address location="http://10.120.147.79:80/sb/ServiceOrderManagement/bundleProvisioning/v/1.0"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>