<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBDesarrollo/Project1/getBolsaIlimitadaXPlan" name="getBolsaIlimitadaXPlan-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBDesarrollo/Project1/getBolsaIlimitadaXPlan" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBDesarrollo/Project1/getBolsaIlimitadaXPlan" location="getBolsaIlimitadaXPlan.wsdl"/>
  <binding name="getBolsaIlimitadaXPlan_ptt-binding" type="tns:getBolsaIlimitadaXPlan_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getBolsaIlimitadaXPlan">
      <soap:operation soapAction="getBolsaIlimitadaXPlan"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getBolsaIlimitadaXPlan-service">
    <port name="getBolsaIlimitadaXPlan-port" binding="tns:getBolsaIlimitadaXPlan_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>