<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getInfoMensajeDba" name="getInfoMensajeDba-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getInfoMensajeDba" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getInfoMensajeDba" location="getInfoMensajeDba.wsdl"/>
  <binding name="getInfoMensajeDba_ptt-binding" type="tns:getInfoMensajeDba_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getInfoMensajeDba">
      <soap:operation soapAction="getInfoMensajeDba"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getInfoMensajeDba-service">
    <port name="getInfoMensajeDba-port" binding="tns:getInfoMensajeDba_ptt-binding">
      <soap:address location="jca://eis/DB/PMEDUSSD"/>
    </port>
  </service>
</definitions>