<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/DateSumVigenciaDba" name="DateSumVigenciaDba-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/DateSumVigenciaDba" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/DateSumVigenciaDba" location="DateSumVigenciaDba.wsdl"/>
  <binding name="DateSumVigenciaDba_ptt-binding" type="tns:DateSumVigenciaDba_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="DateSumVigenciaDba">
      <soap:operation soapAction="DateSumVigenciaDba"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="DateSumVigenciaDba-service">
    <port name="DateSumVigenciaDba-port" binding="tns:DateSumVigenciaDba_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>