<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getMensajeSmsProducto" name="getMensajeSmsProducto-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getMensajeSmsProducto" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getMensajeSmsProducto" location="getMensajeSmsProducto.wsdl"/>
  <binding name="getMensajeSmsProducto_ptt-binding" type="tns:getMensajeSmsProducto_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getMensajeSmsProducto">
      <soap:operation soapAction="getMensajeSmsProducto"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getMensajeSmsProducto-service">
    <port name="getMensajeSmsProducto-port" binding="tns:getMensajeSmsProducto_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>