<?binding.jca getMensajeSmsProducto_db.jca?><wsdl:definitions name="getMensajeSmsProducto" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getMensajeSmsProducto" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/getMensajeSmsProducto" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getMensajeSmsProducto" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="getMensajeSmsProducto_plt">
        <plt:role name="getMensajeSmsProducto_role">
            <plt:portType name="tns:getMensajeSmsProducto_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getMensajeSmsProducto" schemaLocation="getMensajeSmsProducto.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="getMensajeSmsProductoInput_msg">
        <wsdl:part name="getMensajeSmsProductoInput_msg" element="db:getMensajeSmsProductoInput"/>
    </wsdl:message>
    <wsdl:message name="getMensajeSmsProductoOutputCollection_msg">
        <wsdl:part name="getMensajeSmsProductoOutputCollection" element="db:getMensajeSmsProductoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="getMensajeSmsProducto_ptt">
        <wsdl:operation name="getMensajeSmsProducto">
            <wsdl:input message="tns:getMensajeSmsProductoInput_msg"/>
            <wsdl:output message="tns:getMensajeSmsProductoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>