<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/NextDeactiveProdDBA" name="NextDeactiveProdDBA-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/NextDeactiveProdDBA" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/NextDeactiveProdDBA" location="NextDeactiveProdDBA.wsdl"/>
  <binding name="NextDeactiveProdDBA_ptt-binding" type="tns:NextDeactiveProdDBA_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="NextDeactiveProdDBA">
      <soap:operation soapAction="NextDeactiveProdDBA"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="NextDeactiveProdDBA-service">
    <port name="NextDeactiveProdDBA-port" binding="tns:NextDeactiveProdDBA_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>