<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/ProductoCatalogDBA" name="ProductoCatalogDBA-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/ProductoCatalogDBA" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/ProductoCatalogDBA" location="ProductoCatalogDBA.wsdl"/>
  <binding name="ProductoCatalogDBA_ptt-binding" type="tns:ProductoCatalogDBA_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ProductoCatalogDBA">
      <soap:operation soapAction="ProductoCatalogDBA"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ProductoCatalogDBA-service">
    <port name="ProductoCatalogDBA-port" binding="tns:ProductoCatalogDBA_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>