<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/RegistraAltaProductosDBA" name="RegistraAltaProductosDBA-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/RegistraAltaProductosDBA" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/RegistraAltaProductosDBA" location="RegistraAltaProductosDBA.wsdl"/>
  <binding name="RegistraAltaProductosDBA_ptt-binding" type="tns:RegistraAltaProductosDBA_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="RegistraAltaProductosDBA">
      <soap:operation soapAction="RegistraAltaProductosDBA"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="RegistraAltaProductosDBA-service">
    <port name="RegistraAltaProductosDBA-port" binding="tns:RegistraAltaProductosDBA_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>