<?binding.jca setEventoRecargaNoSeqDba_db.jca?><wsdl:definitions name="setEventoRecargaNoSeqDba" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/setEventoRecargaNoSeqDba" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/setEventoRecargaNoSeqDba" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/setEventoRecargaNoSeqDba" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="setEventoRecargaNoSeqDba_plt">
        <plt:role name="setEventoRecargaNoSeqDba_role">
            <plt:portType name="tns:setEventoRecargaNoSeqDba_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/setEventoRecargaNoSeqDba" schemaLocation="setEventoRecargaNoSeqDba.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="setEventoRecargaNoSeqDbaInput_msg">
        <wsdl:part name="setEventoRecargaNoSeqDbaInput_msg" element="db:setEventoRecargaNoSeqDbaInput"/>
    </wsdl:message>
    <wsdl:portType name="setEventoRecargaNoSeqDba_ptt">
        <wsdl:operation name="setEventoRecargaNoSeqDba">
            <wsdl:input message="tns:setEventoRecargaNoSeqDbaInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>