<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/ValidaTransDescDBA" name="ValidaTransDescDBA-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/ValidaTransDescDBA" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/ValidaTransDescDBA" location="ValidaTransDescDBA.wsdl"/>
  <binding name="ValidaTransDescDBA_ptt-binding" type="tns:ValidaTransDescDBA_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ValidaTransDescDBA">
      <soap:operation soapAction="ValidaTransDescDBA"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ValidaTransDescDBA-service">
    <port name="ValidaTransDescDBA-port" binding="tns:ValidaTransDescDBA_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>