<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/NoAws/getInfoPlanCicloDBA" name="getInfoPlanCicloDBA-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/NoAws/getInfoPlanCicloDBA" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/NoAws/getInfoPlanCicloDBA" location="getInfoPlanCicloDba.wsdl"/>
  <binding name="getInfoPlanCicloDBA_ptt-binding" type="tns:getInfoPlanCicloDBA_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getInfoPlanCicloDBA">
      <soap:operation soapAction="getInfoPlanCicloDBA"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getInfoPlanCicloDBA-service">
    <port name="getInfoPlanCicloDBA-port" binding="tns:getInfoPlanCicloDBA_ptt-binding">
      <soap:address location="jca://eis/DB/BSCS"/>
    </port>
  </service>
</definitions>