<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GestorUSSD/WOM.NEG.Fase1.GestorUSSD/BS_GetInfoMensaje" name="BS_GetInfoMensaje-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../../SRV.0010067.getCreditoEmergencia_1.0/Specifications/BS_GetInfoMensaje.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GestorUSSD/WOM.NEG.Fase1.GestorUSSD/BS_GetInfoMensaje"/>
    <wsdl:binding name="BS_GetInfoMensaje_ptt-binding" type="bs:BS_GetInfoMensaje_ptt" xmlns:bs="http://xmlns.oracle.com/pcbpel/adapter/db/GestorUSSD/WOM.NEG.Fase1.GestorUSSD/BS_GetInfoMensaje">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="BS_GetInfoMensaje">
            <soap:operation soapAction="BS_GetInfoMensaje"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>