<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getDatosAbonadoDba" name="getDatosAbonadoDba-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getDatosAbonadoDba" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getDatosAbonadoDba" location="getDatosAbonadoDba.wsdl"/>
  <binding name="getDatosAbonadoDba_ptt-binding" type="tns:getDatosAbonadoDba_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getDatosAbonadoDba">
      <soap:operation soapAction="getDatosAbonadoDba"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getDatosAbonadoDba-service">
    <port name="getDatosAbonadoDba-port" binding="tns:getDatosAbonadoDba_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>