<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getOfertaBucketDba" name="getOfertaBucketDba-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getOfertaBucketDba" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getOfertaBucketDba" location="getOfertaBucketDba.wsdl"/>
  <binding name="getOfertaBucketDba_ptt-binding" type="tns:getOfertaBucketDba_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getOfertaBucketDba">
      <soap:operation soapAction="getOfertaBucketDba"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getOfertaBucketDba-service">
    <port name="getOfertaBucketDba-port" binding="tns:getOfertaBucketDba_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>