<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getPlataformaXPlanDba" name="getPlataformaXPlanDba-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getPlataformaXPlanDba" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getPlataformaXPlanDba" location="getPlataformaXPlanDba.wsdl"/>
  <binding name="getPlataformaXPlanDba_ptt-binding" type="tns:getPlataformaXPlanDba_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getPlataformaXPlanDba">
      <soap:operation soapAction="getPlataformaXPlanDba"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getPlataformaXPlanDba-service">
    <port name="getPlataformaXPlanDba-port" binding="tns:getPlataformaXPlanDba_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>