<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getTecnologiaXPlanDba" name="getTecnologiaXPlanDba-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getTecnologiaXPlanDba" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProviBols/provi_bols/getTecnologiaXPlanDba" location="getTecnologiaXPlanDba.wsdl"/>
  <binding name="getTecnologiaXPlanDba_ptt-binding" type="tns:getTecnologiaXPlanDba_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getTecnologiaXPlanDba">
      <soap:operation soapAction="getTecnologiaXPlanDba"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getTecnologiaXPlanDba-service">
    <port name="getTecnologiaXPlanDba-port" binding="tns:getTecnologiaXPlanDba_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>