<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/timsiBymsisdnDBA" name="timsiBymsisdnDBA-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/timsiBymsisdnDBA" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PortalCautivo/NextelProductCatalog/timsiBymsisdnDBA" location="timsiBymsisdnDBA.wsdl"/>
  <binding name="timsiBymsisdnDBA_ptt-binding" type="tns:timsiBymsisdnDBA_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="timsiBymsisdnDBA">
      <soap:operation soapAction="timsiBymsisdnDBA"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="timsiBymsisdnDBA-service">
    <port name="timsiBymsisdnDBA-port" binding="tns:timsiBymsisdnDBA_ptt-binding">
      <soap:address location="jca://eis/DB/BSCSCORPMAN"/>
    </port>
  </service>
</definitions>